FROM python:3.9-slim
ADD app.py app.py
ADD index.html index.html
ADD mail.txt mail.txt
ADD name.txt name.txt
ADD requirements.txt requirements.txt
RUN pip install -r requirements.txt
ENV CONTAINERENV True
EXPOSE 5000
ENTRYPOINT python3 app.py